# Site settings
title: Cara Nix
email: caramnix@gmail.com
url: caranix.com
description: "Hi, I'm Cara!  I am a data scientist and quantitative researcher with a PhD in political science and an MS in computer science from The Ohio State University."
keywords: "Data Science, Data Analysis, Data Engineer, Politics, Researcher, Machine Learning"
skills: "Data Scientist & Python Enthusiast"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FAF9F6 #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Cara Nix
  location: Contact Me
  social: Let's Connect
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/CaraNix
  - title: github
    url: http://github.com/caramnix
  - title: linkedin
    url: https://www.linkedin.com/in/cara-nix/

# Postal address (add as many lines as necessary)
address:
  - line: caramnix@gmail.com

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com" color=#fff>Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
